<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RollForward>Major</RollForward>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
        <ApplicationIcon>Assets\icon.ico</ApplicationIcon>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <PackId>SyncData</PackId>
        <PackTitle>SyncData</PackTitle>
    </PropertyGroup>

    <ItemGroup>
        <AvaloniaResource Include="Assets\**" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="11.3.22" />
        <PackageReference Include="Avalonia.Desktop" Version="11.3.22" />
        <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.22" />
        <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.22" />
        <PackageReference Include="Avalonia.Diagnostics" Version="11.3.22" Condition="'$(Configuration)' == 'Debug'" />
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
        <PackageReference Include="Velopack" Version="1.0.1" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\SyncData.Core\SyncData.Core.csproj" />
    </ItemGroup>

</Project>
